# Generated by Django 5.1.6 on 2025-03-27 16:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='shop.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField(default=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('authorization_url', models.URLField(blank=True, null=True)),
                ('access_code', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('verified', models.BooleanField(default=False)),
                ('ad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.ad')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='shop.shop')),
            ],
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['shop'], name='ads_ad_shop_id_fff7c6_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['is_active'], name='ads_ad_is_acti_50ada4_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['end_date'], name='ads_ad_end_dat_5be0fd_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['ad'], name='ads_payment_ad_id_a25083_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['owner'], name='ads_payment_owner_i_22c3f0_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='ads_payment_created_2b4d06_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['reference'], name='ads_payment_referen_d9c421_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_status'], name='ads_payment_payment_7bb814_idx'),
        ),
    ]
