# Generated by Django 5.1.6 on 2025-03-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shopvisit_shop_shopvi_shop_id_9c21a6_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='visit_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]