# Generated by Django 5.1.6 on 2025-08-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Latitude of the shop location",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Longitude of the shop location",
                max_digits=9,
                null=True,
            ),
        ),
    ]
